import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "builder",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="mx-auto flex flex-grow w-full">{children}</div>
  );
}