import { ClerkProvider } from "@clerk/nextjs";
import '../globals.css'

export const metadata = {
  title: "Threads-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="font-abc bg-dark-1">
          <div className="w-full min-h-screen flex items-center justify-center">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
